version: "3"

services:
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: copaluser
      MARIADB_PASSWORD: copalpass
      MARIADB_DATABASE: socios_db
    ports:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql

  java_app:
    container_name: java_api
    image: java_app:api
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - URL=jdbc:mariadb://db:3306/socios_db
      - USERNAME=copaluser
      - PASSWORD=copalpass
      - DRIVER=org.mariadb.jdbc.Driver
      - DDL_AUTO=create
      - SHOW_SQL=true
    depends_on:
      - db
